### ISSUE TITLE
Swarm simulation app has no reset function

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/content-slider-apps#10]
The swarm simulation is never reset because it is missing a `reset()` function to revert everything to its initial state. The app also contains several moveable points which can be moved outside or at least almost outside of the app region and it definitely makes sense to reset these. Same with sliders ...

**Comment by montaga** [comment]
Apparently, SwarmSimulation is set to its default state when sliding it in and out within the content-slider, so I do not see demand to implement such a reset functions.
However, I cannot locate the responsible code. Maybe it is related on how CindyJS handles physics simulations.

**Comment by porst17** [comment]
Using it via the single app viewer, I can not reproduce the auto-resetting. Also, it is very inconsistent behavior. Apps should not arbitrarily reset themselves.

This app simply doesn't comply with the intended behavior of the `pause()`, `resume()` and `reset()` functions. Even though it doesn't break our current use case, it is worth figuring out what is going on and why. Because, when our use case breaks, it might be this app and we don't know why.
